name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs_validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          CATEGORY: "plugin"
  language_validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: Language validation
        run: |
          python3 -m pip install colorama setuptools
          python3 -m pip install pyicu
          script -e -c python3 .github/workflows/check.py
